<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQBpIJxe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQBpIJxe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQBpIJxe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQBpIJxe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQBpIJxe\App_KernelDevDebugContainer([
    'container.build_hash' => 'QBpIJxe',
    'container.build_id' => 'a8d70001',
    'container.build_time' => 1730670379,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQBpIJxe');
