<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYzsWZx6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYzsWZx6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYzsWZx6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYzsWZx6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYzsWZx6\App_KernelDevDebugContainer([
    'container.build_hash' => 'YzsWZx6',
    'container.build_id' => 'c8705234',
    'container.build_time' => 1730658623,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYzsWZx6');
