<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKC9cah4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKC9cah4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKC9cah4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKC9cah4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKC9cah4\App_KernelDevDebugContainer([
    'container.build_hash' => 'KC9cah4',
    'container.build_id' => 'b6205b4b',
    'container.build_time' => 1730668641,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKC9cah4');
